language: ruby
rvm: 2.6.3
cache:
  - bundler
env:
  - RAILS_MASTER_KEY=0855c71c381479974b4a80f9cd8969e4 RACK_ENV=test

script:
  - bundle install
  - bundle exec rake spec

# notifications:
#   email:
#     recipients:
#     - thapakazi@dibya.org
#     on_success: always
#     on_failure: always
