version: '3.2'

services:
  db:
    image: postgres:10.1
    container_name: api_db
    environment:
      - POSTGRES_DB=api_development
    ports:
      - "5432:5432"

  redis:
    image: redis:4.0.9
    container_name: api_redis
    ports:
      - "6379:6379"
