version: '3.2'

services:
  db:
    image: postgres:10.1
    container_name: api_db
    environment:
      - POSTGRES_DB=api_test
    ports:
      - "5432"

  redis:
    image: redis:4.0.9
    container_name: api_redis
    ports:
      - "6379"

  test:
    build:
      context: .
      cache_from:
        - ${DOCKER_IMAGE}:${BRANCH_TAG}
      args:
        - RUBY_ENV=test
        - NODE_ENV=test
        - BUILD_ENV=test
    image: ${DOCKER_IMAGE}:${BRANCH_TAG}
    container_name: api_test
    command: bin/test.sh
    stdin_open: true
    tty: true
    depends_on:
      - db
    volumes:
      - "ruby-bundle:/bundle"
      - "${PWD}/tmp/screenshots:/api/tmp/screenshots"
      - "${PWD}/log:/api/log"
    environment:
      - RACK_ENV=test
      - RAILS_ENV=test
      - NODE_ENV=test
      - DB_HOST=db
      - CI=$CI
      - TEST_RETRY=$TEST_RETRY

volumes:
  ruby-bundle:
